# Generated by Django 2.2.12 on 2020-04-21 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='サークル名')),
                ('university', models.CharField(max_length=50, verbose_name='主要大学')),
                ('kind', models.CharField(choices=[('運動系', '運動系'), ('文化系', '文化系'), ('技術系', '技術系'), ('音楽系', '音楽系'), ('委員会系', '委員会系')], max_length=10, verbose_name='サークルの系統')),
                ('is_officially_approved', models.CharField(choices=[('公認', '公認'), ('非公認', '非公認')], max_length=5, verbose_name='大学公認かどうか')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/profile/')),
                ('activity', models.TextField(blank=True, null=True, verbose_name='活動内容')),
                ('message', models.TextField(blank=True, null=True, verbose_name='メッセージ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'club',
                'ordering': ['modified_at'],
            },
        ),
    ]
